# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15W8su0YagScIzPd1J4lobcmKatq-a5dl
"""

import os, shutil

# If folder doesn't exist, create it
os.makedirs("/root/.kaggle", exist_ok=True)

# Now copy the file: path should match where you uploaded it
shutil.copy("/content/kaggle.json", "/root/.kaggle/kaggle.json")
os.chmod("/root/.kaggle/kaggle.json", 0o600)

!pip install kaggle --quiet

import shutil
import os

# Move kaggle.json to the right location
shutil.copy("/content/kaggle.json", "/root/.kaggle/kaggle.json")
os.chmod("/root/.kaggle/kaggle.json", 0o600)

# Download and extract the CXR dataset
!kaggle datasets download -d paultimothymooney/chest-xray-pneumonia
!unzip -q chest-xray-pneumonia.zip

from tensorflow.keras.preprocessing.image import ImageDataGenerator

train_gen = ImageDataGenerator(rescale=1./255).flow_from_directory(
    'chest_xray/train', target_size=(224,224), batch_size=32, class_mode='binary')
val_gen = ImageDataGenerator(rescale=1./255).flow_from_directory(
    'chest_xray/val', target_size=(224,224), batch_size=32, class_mode='binary')
test_gen = ImageDataGenerator(rescale=1./255).flow_from_directory(
    'chest_xray/test', target_size=(224,224), batch_size=32, class_mode='binary')

import tensorflow as tf

base = tf.keras.applications.MobileNetV2(input_shape=(224,224,3), include_top=False, weights='imagenet')
base.trainable = False
model = tf.keras.Sequential([
    base,
    tf.keras.layers.GlobalAveragePooling2D(),
    tf.keras.layers.Dense(1, activation='sigmoid')
])
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.fit(train_gen, validation_data=val_gen, epochs=3)

loss, acc = model.evaluate(test_gen)
print(f'Test accuracy: {acc:.2%}')

model.save('cxr_pneumonia_model.h5')

from google.colab import drive
drive.mount('/content/drive')